// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwKXETae07xMOlwAEWkWM3hanOeS6OR0',
    appId: '1:583650894277:web:b966d9102f580ca0edabac',
    messagingSenderId: '583650894277',
    projectId: 'ditmenavi3',
    authDomain: 'ditmenavi3.firebaseapp.com',
    databaseURL: 'https://ditmenavi3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditmenavi3.appspot.com',
    measurementId: 'G-G8C1HV7KHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsL3y8P_ODT0v5IAOyroJtegItUoxdxM',
    appId: '1:583650894277:android:af13f25427ff4b5eedabac',
    messagingSenderId: '583650894277',
    projectId: 'ditmenavi3',
    databaseURL: 'https://ditmenavi3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditmenavi3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnaxiDerIj_B01ju4WRx9MFPGl3MLs2Y',
    appId: '1:583650894277:ios:2aaeac9e0be5c665edabac',
    messagingSenderId: '583650894277',
    projectId: 'ditmenavi3',
    databaseURL: 'https://ditmenavi3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditmenavi3.appspot.com',
    iosClientId: '583650894277-u0qbissee2arblr71vbfupnq5sc5eooq.apps.googleusercontent.com',
    iosBundleId: 'com.neekowo.ditmenavi3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnaxiDerIj_B01ju4WRx9MFPGl3MLs2Y',
    appId: '1:583650894277:ios:85e262f663e27d4aedabac',
    messagingSenderId: '583650894277',
    projectId: 'ditmenavi3',
    databaseURL: 'https://ditmenavi3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ditmenavi3.appspot.com',
    iosClientId: '583650894277-b4kpkv7ri9vi5u60vr0248vuhou5k1af.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditmenavi3',
  );
}
